### ISSUE TITLE
Cursor location displayed weirdly

### ISSUE THREAD

**Issue by colus001** [teddybradford/atom-trendy-light-ui#8] opened 2015-05-14 05:45 UTC
Not sure what's happening here but my cursor and block doesn't display correctly.
I attached screen shots below

![screen shot 2015-05-14 at 2 40 22 pm](https://cloud.githubusercontent.com/assets/2831540/7626645/840062fa-fa47-11e4-83b2-a557da2d3605.png)

![screen shot 2015-05-14 at 2 40 29 pm](https://cloud.githubusercontent.com/assets/2831540/7626663/a6d31ade-fa47-11e4-8992-c0b56a13ce5c.png)

I thought it might occur because of syntax theme.
So I tried one you made.

![screen shot 2015-05-14 at 2 41 58 pm](https://cloud.githubusercontent.com/assets/2831540/7626671/c1e18b4e-fa47-11e4-9562-14cc26c11fb9.png)

It has same result. I also tried with different font but it has same result as above.
Not sure only I'm suffering from these problems.
Any fixes?

**Comment by teddybradford** [comment] 2015-06-25 14:25
This seems to be a duplicate of #4.

**Closed by teddybradford** 2015-06-25 14:25 UTC
